# Generated by Django 3.1.7 on 2021-03-02 06:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweet_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 2, 6, 43, 50, 94183, tzinfo=utc), verbose_name='date tweeted'),
        ),
    ]
