# Generated by Django 3.1.7 on 2021-03-02 06:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210302_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweet_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date tweeted'),
        ),
    ]
